In [2]:
import numpy as np
x=np.array([1,2,3,4,5])
print(x)


[1 2 3 4 5]


In [52]:
print(type(x))
print(x.flatten())


<class 'numpy.ndarray'>
[1 2 3 4 5 6 7 6 4 8 9 0 1 2 3]


In [9]:
print(np.arange(1,10,5))

[1 6]


In [10]:
print(np.linspace(1,10,5))

[ 1.    3.25  5.5   7.75 10.  ]


In [11]:
import numpy as np
x=np.array([1,2,3,4,5,6])
print(x.reshape(2,3))

[[1 2 3]
 [4 5 6]]


In [12]:
print(x.size)

6


In [13]:
print(x.shape)

(6,)


In [14]:
print(x.dtype)

int32


In [15]:
print(x.itemsize)

4


In [17]:
print(np.zeros([5,5]))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [18]:
print(np.ones([3,4]))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [21]:
print(np.random.random([4,5]))

[[0.38763999 0.23900181 0.93694408 0.70188584 0.93157789]
 [0.17967176 0.68157577 0.78749571 0.75253865 0.80034551]
 [0.1813678  0.8232233  0.491892   0.90780459 0.60431796]
 [0.88786343 0.6493652  0.34795681 0.37481567 0.87279814]]


In [23]:
print(np.random.randint(0,10,5))

[5 1 0 3 6]


In [24]:
print(np.random.shuffle(x))

None


In [26]:
print(np.random.choice(x))

6


In [27]:
import numpy as np
a=np.arange(15)
print(a[3:9:2])

[3 5 7]


In [28]:
import numpy as np
x=np.array([1,2,3,4,5,6])
y=np.array([7,8,9,10,11,12])
print(x+y)

[ 8 10 12 14 16 18]


In [29]:
print(x-y)
print(x*y)
print(x/y)


[-6 -6 -6 -6 -6 -6]
[ 7 16 27 40 55 72]
[0.14285714 0.25       0.33333333 0.4        0.45454545 0.5       ]


In [30]:
print(np.mean(x))
print(np.mean(y))

3.5
9.5


In [31]:
print(np.median(x))
print(np.median(y))

3.5
9.5


In [63]:
print(np.max(x))
print(np.min(y))
print(x.sum())
print(y.min())
print(y.var())
print(x.std())

9
1
39
1
8.916666666666666
1.707825127659933


In [36]:
import numpy as np
x=np.array([[1,2,3],[2,3,4]])
print(x)
print(x.sum(axis=1))


[[1 2 3]
 [2 3 4]]
[6 9]


In [60]:
import numpy as np
x=np.array([4,5,6])
y=np.array([10,10,10])
c = x*y
print(c)  
print(np.concatenate((x,y)))





[40 50 60]
[ 4  5  6 10 10 10]


In [53]:
import numpy as np
x=np.array([[1,2,3,4,5],[6,7,6,4,8],[9,0,1,2,3]])
print(x.ravel())
print(x.flatten())

[1 2 3 4 5 6 7 6 4 8 9 0 1 2 3]
[1 2 3 4 5 6 7 6 4 8 9 0 1 2 3]


In [62]:
import numpy as np
x=np.array([[4,5,6],[7,8,9]])
y=np.array([[1,2,3],[9,8,4]])
print(np.add(x,y))
print(np.sub(x,y))
print(np.matmul(x,y))
print(np.divide(x,y))
print(np.matlib.empty((3,3)))
print(np.matlib.zeros((3,3)))
print(np.matlib.ones((2,2)))
print(np.matlib.identity(3,dtype=float))
print(np.matlib.rand(3,3))
print(np.linalg.det(x))

[[ 5  7  9]
 [16 16 13]]


AttributeError: module 'numpy' has no attribute 'sub'