In [1]:
import numpy as np
from sklearn import decomposition
X = np.array([[2,6],[1,7]])

print("Orginal Matrx X and its Shape")
print(X)
print("Original Shape:",X.shape)
print("Original matrix\n\n")

pca = decomposition.PCA(n_components=2)
X_pca = pca.fit_transform(X)

print("Transformed Matrix and its Shape")
print(X_pca)
print("Transformed Shape:",X_pca.shape)
print("Transformed Matrix\n\n")
print("After Inverse Transform")
X_new=pca.inverse_transform(X_pca)
print(X_new)
print("After Inverse Transform\n\n\n")
print('Explained variance\n')
print(pca.explained_variance_ratio_)
print('completed\n\n')
print('Singular values')
print(pca.singular_values_)
print('completed\n\n')




Orginal Matrx X and its Shape
[[2 6]
 [1 7]]
Original Shape: (2, 2)
Original matrix


Transformed Matrix and its Shape
[[ 7.07106781e-01 -1.18606713e-17]
 [-7.07106781e-01 -1.18606713e-17]]
Transformed Shape: (2, 2)
Transformed Matrix


After Inverse Transform
[[2. 6.]
 [1. 7.]]
After Inverse Transform



Explained variance

[1.00000000e+00 2.81351049e-34]
completed


Singular values
[1.00000000e+00 1.67735223e-17]
completed


