In [2]:
import numpy as np
from numpy.linalg import eig
X = np.array([[3, 6], [4,7]])
print("Orginal Matrx X and its Shape")
print(X)
print("Original matrix Shape")
print("Original Shape:",X.shape)
#Mean
M = np.mean(X.T, axis=1)
print("\nMean matrix")
print(M)
#Center of the mean
C = X - M
print("\nCentre the matrix")
print(C)
# covariance
V = np.cov(C.T)
print("\nCovariance of the matrix\n")
print(V)
# eigen values and vetcors
values, vectors = eig(V)
print('\n Eigen vectors')
print(vectors)
print('\n Eigen values')
print(values)


Orginal Matrx X and its Shape
[[3 6]
 [4 7]]
Original matrix Shape
Original Shape: (2, 2)

Mean matrix
[3.5 6.5]

Centre the matrix
[[-0.5 -0.5]
 [ 0.5  0.5]]

Covariance of the matrix

[[0.5 0.5]
 [0.5 0.5]]

 Eigen vectors
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

 Eigen values
[1.00000000e+00 1.11022302e-16]
